### ISSUE TITLE
Cutting Secret Key in api.dibspayment.eu/v1/payments/ call

### ISSUE THREAD

**Issue by Emetico** [vendrcontrib/vendr-payment-provider-nets#1]
Hi.

After many hours of debugin. We found out that the payment provider cut the secret key for the authorization header in some cases.
Cause it works with the keys from test and we also got another solution that works in LIVE.

In our case it's cutting the first letter 'c', even if we apply the live-checkout-key- infront of it.

We think its because of the `.TrimStart(prefix.ToCharArray())` at https://github.com/vendrcontrib/vendr-payment-provider-nets/blob/f5542a1fda2d2a08159b8bdf72b3f84f121a1ae1/src/Vendr.Contrib.PaymentProviders.Nets/Easy/NetsEasyOneTimePaymentProvider.cs#:~:text=var%20auth%20%3D%20secretKey%3F.Trim().TrimStart(prefix.ToCharArray())%3B that might need to replaced with .Replace(prefix, string.Empty) or something similare.

**Comment by mattbrailsford** [comment]
Makes sense. Trimming a char array means it’ll remove any number of those chars from the front of the string regardless of order where as it’s the exact term that needs to be removed.

**Comment by bjarnef** [comment]
Yeah, it suprises me that Nets Easy doesn't allow to generate new keys like most other payment gateways. Then a temporary workaround would be to generate new keys for live environment.

Umbraco has a extension method for this: `TrimStart(string value, string forRemoving)`:
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Core/Extensions/StringExtensions.cs#L317-L327

In .NET Framework the `TrimStart()` and `TrimEnd()` methods only took an argument of `char[]`. Not sure if this has changed in .NET Core, but the Umbraco extension methods are available in v9 as well.

But yeah, `.Replace()` or `.Substring()` should work.

We need to fix this in v2 as well before release 😅

**Comment by Emetico** [comment]
Even if it was possible, you might end up with some people still having to debug this in order to find out that they need to change the keys.

Would you prefer i do the change and commit to github or will you do it yourself?

And when do you think we can get the hands on the fixed version? :)

**Comment by bjarnef** [comment]
Yes, it isn't a fix, but a workaround 😉 (if it was possible to generate new keys in Nets Easy portal).

Feel free to submit a PR target [v1/dev](https://github.com/vendrcontrib/vendr-payment-provider-nets/tree/v1/dev) branch 👍

**Comment by bjarnef** [comment]
Fixed in https://github.com/vendrcontrib/vendr-payment-provider-nets/pull/2
