### ISSUE TITLE
Customer information not being saved

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrcontrib/vendr-payment-provider-nets#3]
Customer information not being saved on payments. 

I've enteres the correct aliases, but even name is not being saved.
https://prnt.sc/26nrhp9

Umbraco 8.17.2
Vendr 2.0.4
Vendr.Contrib.PaymentProviders.Nets 2.0.0-rc0001

**Comment by bjarnef** [comment]
Hi Michael

That is strange, but I can confirm it is an issue with the recent payments I have tested, where consumer name isn't set in Nets Easy portal.

It the legacy docs of Nets Easy it says:
https://tech.dibspayment.com/easy/api/paymentapi

> - consumer -  add consumer data, EASY will use the postalCode and email address to try and recognize the consumer to load saved payment methods.
>   - privatePerson - either pass "privatePerson" or "company"
>   - company - either pass "privatePerson" or "company"

which it does here:
https://github.com/vendrcontrib/vendr-payment-provider-nets/blob/v2/dev/src/Vendr.Contrib.PaymentProviders.Nets/Easy/NetsEasyOneTimePaymentProvider.cs#L314-L334

A raw JSON example of the request using company field:

```
{
   "order":{
      "reference":"ORDER-00764-31791-3SQL8",
      "currency":"DKK",
      "amount":10000,
      "items":[
         {
            "reference":"GP020-50",
            "name":"Good and Proper - Iron Buddha - 50g",
            "quantity":1,
            "unit":"pcs",
            "unitPrice":8264,
            "taxRate":2100,
            "taxAmount":1736,
            "grossTotalAmount":10000,
            "netTotalAmount":8264
         },
         {
            "reference":"1623",
            "name":"Pickup",
            "quantity":1,
            "unit":"pcs",
            "unitPrice":0,
            "taxRate":2100,
            "taxAmount":0,
            "grossTotalAmount":0,
            "netTotalAmount":0
         }
      ]
   },
   "checkout":{
      "charge":false,
      "publicDevice":false,
      "integrationType":"HostedPaymentPage",
      "cancelUrl":"https://vendr.local/umbraco/vendr/payment/cancel/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/b662f35528eda03167ea780a982091b222acbba3",
      "returnUrl":"https://vendr.local/umbraco/vendr/payment/continue/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/2229a71cd34c20822d6f77b43c203f6f3768be7b",
      "termsUrl":"https://vendr.net/",
      "merchantTermsUrl":"https://vendr.net/docs",
      "appearance":{
         "displayOptions":{
            "showMerchantName":true,
            "showOrderSummary":true
         },
         "textOptions":null
      },
      "merchantHandlesConsumerData":true,
      "consumer":{
         "reference":null,
         "email":"test@mail.dk",
         "shippingAddress":null,
         "phoneNumber":null,
         "privatePerson":null,
         "company":{
            "name":"Test",
            "contact":{
               "firstName":"Test",
               "lastName":"Test"
            }
         }
      }
   },
   "notifications":{
      "webhooks":[
         {
            "eventName":"payment.checkout.completed",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/80069e9f0c606c1bae943d03505a171a9fd3ad85",
            "authorization":"730a3b9f-bfc2-4a2b-a248-7c553bb11610",
            "headers":null
         },
         {
            "eventName":"payment.charge.created",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/80069e9f0c606c1bae943d03505a171a9fd3ad85",
            "authorization":"730a3b9f-bfc2-4a2b-a248-7c553bb11610",
            "headers":null
         },
         {
            "eventName":"payment.refund.completed",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/80069e9f0c606c1bae943d03505a171a9fd3ad85",
            "authorization":"730a3b9f-bfc2-4a2b-a248-7c553bb11610",
            "headers":null
         },
         {
            "eventName":"payment.cancel.created",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-31791-3SQL8/80069e9f0c606c1bae943d03505a171a9fd3ad85",
            "authorization":"730a3b9f-bfc2-4a2b-a248-7c553bb11610",
            "headers":null
         }
      ]
   },
   "paymentMethods":null
}
```

and a similar request just with private person instead:

```
{
   "order":{
      "reference":"ORDER-00764-33447-34MYS",
      "currency":"DKK",
      "amount":10000,
      "items":[
         {
            "reference":"GP020-50",
            "name":"Good and Proper - Iron Buddha - 50g",
            "quantity":1,
            "unit":"pcs",
            "unitPrice":8264,
            "taxRate":2100,
            "taxAmount":1736,
            "grossTotalAmount":10000,
            "netTotalAmount":8264
         },
         {
            "reference":"1623",
            "name":"Pickup",
            "quantity":1,
            "unit":"pcs",
            "unitPrice":0,
            "taxRate":2100,
            "taxAmount":0,
            "grossTotalAmount":0,
            "netTotalAmount":0
         }
      ]
   },
   "checkout":{
      "charge":false,
      "publicDevice":false,
      "integrationType":"HostedPaymentPage",
      "cancelUrl":"https://vendr.local/umbraco/vendr/payment/cancel/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/50d2aa6b0deaebf30c2bfb84e2e1a4519dc72575",
      "returnUrl":"https://vendr.local/umbraco/vendr/payment/continue/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/dcf3c31c3d9feea15f028c0274acafcb2665f731",
      "termsUrl":"https://vendr.net/",
      "merchantTermsUrl":"https://vendr.net/docs",
      "appearance":{
         "displayOptions":{
            "showMerchantName":true,
            "showOrderSummary":true
         },
         "textOptions":null
      },
      "merchantHandlesConsumerData":true,
      "consumer":{
         "reference":null,
         "email":"test@mail.dk",
         "shippingAddress":null,
         "phoneNumber":null,
         "privatePerson":{
            "firstName":"Test",
            "lastName":"Test"
         },
         "company":null
      }
   },
   "notifications":{
      "webhooks":[
         {
            "eventName":"payment.checkout.completed",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/9948983f4b4b90cdd464c1f2ac3eb1ec95fa67f6",
            "authorization":"989ffe23-df99-471f-b3e5-88141f5c8940",
            "headers":null
         },
         {
            "eventName":"payment.charge.created",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/9948983f4b4b90cdd464c1f2ac3eb1ec95fa67f6",
            "authorization":"989ffe23-df99-471f-b3e5-88141f5c8940",
            "headers":null
         },
         {
            "eventName":"payment.refund.completed",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/9948983f4b4b90cdd464c1f2ac3eb1ec95fa67f6",
            "authorization":"989ffe23-df99-471f-b3e5-88141f5c8940",
            "headers":null
         },
         {
            "eventName":"payment.cancel.created",
            "url":"https://vendr.local/umbraco/vendr/payment/callback/nets-easy-checkout-onetime/1d171a92-2e5d-45c5-b351-017ea6639b21/ORDER-00764-33447-34MYS/9948983f4b4b90cdd464c1f2ac3eb1ec95fa67f6",
            "authorization":"989ffe23-df99-471f-b3e5-88141f5c8940",
            "headers":null
         }
      ]
   },
   "paymentMethods":null
}
```

Not sure if Nets has changed something since this was also how it worked in v1:
https://github.com/vendrcontrib/vendr-payment-provider-nets/blob/v1/dev/src/Vendr.Contrib.PaymentProviders.Nets/Easy/NetsEasyOneTimePaymentProvider.cs#L308-L328

I know some payment gateways want specific properties to be omitted and not just include with a `null` value.

**Comment by bjarnef** [comment]
Nets explains:

> From the documentation I can se that "merchantHandlesConsumerData" is set to true which means that no customer information is saved when the payment is done.
> 
> You can read more here: https://developers.nets.eu/nets-easy/en-EU/docs/optimize-the-checkout-flow/#optimize-the-checkout-flow

However setting `merchantHandlesConsumerData = false` means customer information fields are shown in payment window, which is okay in embedded checkout, but we don't want that in Hosted Payment Window as these are already handled in checkout.

and it clearly did work sometime ago:

![image](https://user-images.githubusercontent.com/2919859/152511867-23296862-9222-44e6-90ee-bbb09694163b.png)


From docs they are mentioning: https://developers.nets.eu/nets-easy/en-EU/api/payment-v1/#v1-payments-post-body-checkout-merchanthandlesconsumerdata

![image](https://user-images.githubusercontent.com/2919859/152512077-416adcce-6636-4a0a-9e43-1589d327aca6.png)

They don't say anything about the consumer data won't be saved.

To me it seems like Nets has changed something, which cause this doesn't work anymore.

**Comment by MichaelNielsenDK** [comment]
Hmm... Nets should just save customer data when it's sent to them, but oh well 🤷‍♂️

Thanks for looking into this.

**Comment by bjarnef** [comment]
I have checked this again with various test payments "Visa" and "Master Card", as private person and company, with/without phone number, but consumer name is always empty unless I set `"merchantHandlesConsumerData": false`, which also shows customer/billing details in payment window and then works. This may work in a embedded checkout, but not so much in a Hosted payment window.

I don't know why Nets broke this, but I asked then why and hopefully they will escalate this issue.

![image](https://user-images.githubusercontent.com/2919859/153258892-6a6dc741-9ecd-4600-9db8-20a1f00518c8.png)

**Comment by bjarnef** [comment]
I have tested a few payment using `"merchantHandlesConsumerData": true` which doesn't set consumer in Nets Easy.

However I noticed when setting `shippingAddress: null` and "privatePerson": { "firstName": "Test", "lastName": "Test" }` in Nets Easy it sets consumer `Test NETS` (which was from a previous payment).

When I then used same consumer name, but set the following `shippingAddress`.

```
"shippingAddress": {
    "addressLine1": "Test adress",
    "addressLine2": "",
    "postalCode": "7400",
    "city": "Herning",
    "country": "DNK"
}
```

it did use "Test Test" as consumer name.

`shippingAddress` is set if values exists for all of the following properties otherwise `null`:
https://github.com/vendrcontrib/vendr-payment-provider-nets/blob/v2/dev/src/Vendr.Contrib.PaymentProviders.Nets/Easy/NetsEasyOneTimePaymentProvider.cs#L275-L288

`"privatePerson": { "firstName": "Test", "lastName": "Test" }` was submitted in the top 6 payments here, but the two payment which shows `Test NETS` was requested with `"shippingAddress": null`


![image](https://user-images.githubusercontent.com/2919859/154684852-eeb742f1-9f3a-43d7-9f8b-f27fc80d2030.png)

It is probably because the same consumer `"email": "test@mail.uk"` was used, so Nets identify the consumer and use the existing consumer I guess.

**Comment by bjarnef** [comment]
From Nets:

> Yes, we use cookies to identify consumers and since you have already been to that checkout page, the system will try to use those data. Try pasting the url into Incognito mode or change the "publicDevice" to true and that should not happen again.

> Yes, because if both email and zipcode/address isn't available, we don't save the rest of the data.

![image](https://user-images.githubusercontent.com/2919859/154696039-96a7679f-dbef-4d2d-8ac3-c8b4d6c47d6d.png)

https://developers.nets.eu/nets-easy/en-EU/support/is-the-consumer-information-i-pass-on-to-nets-going-to-be-st/

**Comment by bjarnef** [comment]
> Yes, that is the correct behavior. If you have the merchant handles consumer data enabled, we'll only save the details in the portal if you provide us all the information as in my test example. If you don't send a shipping address other data will be ignored as well.


![image](https://user-images.githubusercontent.com/2919859/155527597-b949bf46-b839-4d75-811e-ea260fef0358.png)


There is typo in there's a typo here in `merchantHandlesConsumerData` in their documentation here: https://developers.nets.eu/nets-easy/en-EU/support/is-the-consumer-information-i-pass-on-to-nets-going-to-be-st/

So ensure the the required data is specified and no dummy data is submitted. If the customer previous has completed checkout, Nets may identify the consumer and may identify from previous cookie value.
