### ISSUE TITLE
Customer name not sent to nets

### ISSUE THREAD

**Issue by NicolaiJee** [vendrcontrib/vendr-payment-provider-nets#5]
Hi
We have a Vendr installation with version 2.0 of this provider.
It works fine but customer name is not shown in Nets.
Do we need to do something special to make this happen ?

**Comment by bjarnef** [comment]
It may be the same as reported here: https://github.com/vendrcontrib/vendr-payment-provider-nets/issues/3

However the way Nets Easy work they identify an existing consumer by using the cookie value.
Furthermore Nets don't store consumer if zipcode/address isn't available:
https://github.com/vendrcontrib/vendr-payment-provider-nets/issues/3#issuecomment-1044567191

You may also need to ensure the shipping address properties get data from the matching order properties and the properties have values as well.

**Comment by NicolaiJee** [comment]
So I need to fill out these fields ?
![image](https://user-images.githubusercontent.com/2285823/165492925-c593af93-1a70-4ad0-9b13-71019022fa2e.png)

**Comment by NicolaiJee** [comment]
I did look at the other issue, but wasn't sure what I need to do in order to make it work.

**Comment by bjarnef** [comment]
Yes, otherwise it doesn't set shipping address and I believe it's a requirement from Nets to store consumer on the payment.
https://github.com/vendrcontrib/vendr-payment-provider-nets/blob/v2/dev/src/Vendr.Contrib.PaymentProviders.Nets/Easy/NetsEasyOneTimePaymentProvider.cs#L275-L288

Hopefully in future versions of Vendr, we get a bit more control of properties, e.g. tabs, groups, make specific properties mandatory and maybe even decide the property editor to use.

// cc @mattbrailsford

**Comment by NicolaiJee** [comment]
HI Bjarne
I tried setting the properties but ended up with this error:
![image](https://user-images.githubusercontent.com/2285823/165752038-ad615bab-95f5-4f5b-b6a1-c4bb59c3815c.png)

All the fields have been set, and I have ensured that there are a value in all of those properties.
![image](https://user-images.githubusercontent.com/2285823/165752252-ca0360dc-602e-4bec-8c23-2d9028499ee4.png)

I can see others have had this error but I am unsure what the solution was.
Hope you can help me :)

**Comment by bjarnef** [comment]
Does phone property contains a valid format, e.g. "+4512345678"? Currently it split the first 3 characters to use as prefix and the ones as number.

Phone isn't required but when set is must both contain a value prefix and number.

I also think Terms URL is mandatory.

Does the log show a more specific error?

**Comment by NicolaiJee** [comment]
Terms url has been set.
I removed phone number and now I goes to the payment page.
Thanks for your help.

**Comment by bjarnef** [comment]
Great.. I wonder if which format the phone number was specified?

**Comment by NicolaiJee** [comment]
It is a danish only page so just 8 digits :)

**Comment by bjarnef** [comment]
For example it works with "+45", but with "45" the request fails.

![image](https://user-images.githubusercontent.com/2919859/165757714-0ce68137-81ce-49de-958e-1af3655cdbb9.png)

Strange enough Nets shows "001" in the example here, but it fails. Also "045" doesn't seem to be valid.
https://developers.nets.eu/nets-easy/en-EU/api/payment-v1/#v1-payments-post

Or at least it need `+` in start of string.

**Comment by NicolaiJee** [comment]
Not the first time Nets has bad description or badly updated documentation.
My client just wanted the customer name not so much phone and all that :)

**Comment by bjarnef** [comment]
Yeah, the documentation has been updated, but still there are various parts which isn't fully updated.
We could probably adjust the code to add a `+` in case phone property value doesn't start with a plus.
